name: "Multi Layer UI"

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            conan_compiler: "Visual Studio"
            cxx: "cl"
            compiler_version: 17
            
          - os: ubuntu-22.04
            conan_compiler: "clang"
            cxx: "clang++"
            compiler_version: 14
            
          - os: macos-12
            conan_compiler: "apple-clang"
            cxx: "clang++"
            compiler_version: 14
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Setup Environment
      run:
        pip install conan
        pip install ninja

    - name: Install Dependencies
      run: |
        python conan/profile.py '${{matrix.conan_compiler}}' ${{matrix.compiler_version}}
        python conan/install.py ${{env.BUILD_TYPE}} '${{matrix.conan_compiler}}${{matrix.compiler_version}}'

    - name: Configure
      env:
        CXX: ${{ matrix.cxx }}
      run: |
        cmake -G Ninja -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/build/${{env.BUILD_TYPE}} -S . 

    - name: Build
      env:
        CXX: ${{ matrix.cxx }}
      run: |
        cmake --build ${{github.workspace}}/build/${{env.BUILD_TYPE}} --config ${{env.BUILD_TYPE}}
