name: "Multi Layer UI"

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            cc: "Visual Studio"
            cxx: "Visual Studio"
            compiler_version: 17
            
          - os: ubuntu-22.04
            cc: "clang"
            cxx: "clang++"
            compiler_version: 14
            
          - os: macos-12
            cc: "apple-clang"
            cxx: "apple-clang"
            compiler_version: 14
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Setup Environment
      run:
        pip install conan
        pip install ninja

    - name: Install Dependencies
      run: |
        python conan/profile.py '${{matrix.cc}}' ${{matrix.compiler_version}}
        python conan/install.py ${{env.BUILD_TYPE}} '${{matrix.cc}}${{matrix.compiler_version}}'

    - name: Configure
      if: ${{ contains(matrix.os, 'ubuntu') }}
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        cmake -G Ninja -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/build/${{env.BUILD_TYPE}} -S . 

    - name: Configure
      if: ${{ contains(matrix.os, 'macos') }}
      env:
        CC: clang
        CXX: clang++
      run: |
        cmake -G Ninja -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/build/${{env.BUILD_TYPE}} -S . 

    - name: Configure
      if: contains(matrix.os, 'windows')
      env:
        CC: cl
        CXX: cl
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -G Ninja -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/build/${{env.BUILD_TYPE}} -S . 

    - name: Build
      if: ${{ contains(matrix.os, 'ubuntu') }}
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        cmake --build ${{github.workspace}}/build/${{env.BUILD_TYPE}} --config ${{env.BUILD_TYPE}}
   
    - name: Build
      if: ${{ contains(matrix.os, 'macos') }}
      env:
        CC: clang
        CXX: clang++
      run: |
        cmake --build ${{github.workspace}}/build/${{env.BUILD_TYPE}} --config ${{env.BUILD_TYPE}}

    - name: Build
      if: contains(matrix.os, 'windows')
      env:
        CC: cl
        CXX: cl
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake --build ${{github.workspace}}/build/${{env.BUILD_TYPE}} --config ${{env.BUILD_TYPE}}
    
